---

- hosts: controllers
  remote_user: ubuntu
  roles:
    - {role: common}
    - {role: mysql}
    - {role: apache}
    - {role: memcached}
    - {role: rabbitmq}
    - {role: keystone}
    - {role: glance}
    - {role: nova-controller}
    - {role: neutron}

- hosts: computes
  remote_user: ubuntu
  roles:
      - {role: common}
      - {role: nova-compute}
