---

nova_compute_pkgs:
          - "nova-compute"

nova_compute_service: 
        - "nova-compute"

nova_conf_dir: "/etc/nova"

nova_compute_conf:
    DEFAULT:
        transport_url: "rabbit://openstack:{{ rabbit_pass }}@controller"
        my_ip: "{{ management_interface_address_compute| default('10.0.0.2') }}"
        use_neutron: True
        firewall_driver: "nova.virt.firewall.NoopFirewallDriver"
        dhcpbridge_flagfile: "/etc/nova/nova.conf"
        dhcpbridge: "/usr/bin/nova-dhcpbridge"
        state_path: "/var/lib/nova"
        force_dhcp_release: True
        verbose: True
        ec2_private_dns_show_ip: True
        enabled_apis: "osapi_compute,metadata"
    api:
        auth_strategy: "keystone"
    keystone_authtoken:
        auth_uri: "http://controller:5000"
        auth_url: "http://controller:35357"
        memcached_servers: "controller:11211"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        project_name: "service"
        username: "nova"
        password: "{{ nova_pass }}"
    vnc:
        enabled: True
        vncserver_listen: "0.0.0.0"
        vncserver_proxyclient_address: "$my_ip"
        novncproxy_base_url: "http://controller:6080/vnc_auto.html"
    glance:
        api_servers: "http://controller:9292"
    oslo_concurrency:
        lock_path: "/var/lib/nova/tmp"
    libvirt:
        use_virtio_for_bridges: True
    wsgi:
        api_paste_config: "/etc/nova/api-paste.ini"
    database:
        connection: "connection=sqlite:////var/lib/nova/nova.sqlite"
    api_database:
        connection: "connection=sqlite:////var/lib/nova/nova.sqlite"
    neutron:
        url: "http://controller:9696"
        auth_url: "http://controller:35357"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        region_name: "RegionOne"
        project_name: "service"
        username: "neutron"
        password: "{{ neutron_pass }}"
    placement:
        os_region_name: "RegionOne"
        project_domain_name: "Default"
        project_name: "service"
        auth_type: "password"
        user_domain_name: "Default"
        auth_url: "http://controller:35357/v3"
        username: "placement"
        password: "{{ placement_pass }}"
