---

- name: Install neutron compute node packages
  become: yes
  apt: 
      name: "{{ item }}"
      state: "latest"
      update_cache: yes
  with_items: neutron_compute_pkgs

- name: Change neutron config file on compute node
  become: yes
  template:
      src: "neutron-compute.j2"
      dest: "{{ neutron_conf_dir }}/neutron.conf"

- name: Change ml2 linuxbridge agent config file on compute node
  become: yes
  template:
      src: "linuxbridge-compute.j2"
      dest: "{{ ml2_plugin_conf_dir }}/linuxbridge_agent.ini"

- name: Restart the Networking services on compute node
  become: yes
  service:
      name: "{{ item}}"
      state: "restarted"
  with_items: neutron_compute_services
