---

- name: Create cinder user
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  os_user:
      state: "present"
      name: "cinder"
      password: "{{ cinder_pass }}"
      domain: "default"
      enabled: True

- name: Add the admin role to the cinder user and service project
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  shell: "openstack role add --project service --user cinder admin"

- name: Create the cinder service entity
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  #os_keystone_service:
  #    state: present
  #    name: cinder
  #    description: "OpenStack Block Storage"
  #    service_type: "volume"
  shell: 'openstack service create --name cinder --description "OpenStack Block Storage" volume'

- name: Create the cinderv2 service entity
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  #os_keystone_service:
  #    state: present
  #    name: cinderv2
  #    description: "OpenStack Block Storage"
  #    service_type: "volumev2"
  shell: 'openstack service create --name cinderv2 --description "OpenStack Block Storage" volumev2'


- name: Create the Block Storage service API endpoints
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  shell: "openstack endpoint create --region RegionOne volume public http://controller:8776/v1/%\\(tenant_id\\)s \
          openstack endpoint create --region RegionOne volume internal http://controller:8776/v1/%\\(tenant_id\\)s; \
          openstack endpoint create --region RegionOne volume admin http://controller:8776/v1/%\\(tenant_id\\)s; \
          openstack endpoint create --region RegionOne volumev2 public http://controller:8776/v2/%\\(tenant_id\\)s; \
          openstack endpoint create --region RegionOne volumev2 internal http://controller:8776/v2/%\\(tenant_id\\)s; \
          openstack endpoint create --region RegionOne volumev2 admin http://controller:8776/v2/%\\(tenant_id\\)s; "

- name: Install cinder packages to controller
  become: yes
  apt: 
      name: "{{ item }}"
      state: "latest"
      update_cache: yes
  with_items: "{{ cinder_controller_pkgs }}"

- name: Change cinder config file on controller node
  become: yes
  template:
      src: "cinder-controller.j2"
      dest: "{{ cinder_conf_dir }}/cinder.conf"

- name: Populate the Block Storage service database
  become: yes
  shell: 'su -s /bin/sh -c "cinder-manage db sync" cinder'

- name: Restart the cinder services on controller node
  become: yes
  service:
      name: "{{ item}}"
      state: "restarted"
  with_items: "{{ cinder_controller_services }}"
