---

- name: Install the mysql packages
  become: yes
  apt: 
      name: "{{ item }}" 
      state: "latest" 
      update_cache: yes
  with_items: "{{ mysql_pkgs }}"

- name: Copy openstack specific config file 
  become: yes
  template: 
      src: "openstack.j2"
      dest: "{{ openstack_mysql_conf_dir }}/openstack.cnf"
  #notify: restart mysql

- name: Comment out bind address
  become: yes
  replace:
      dest: "{{ mysql_conf_dir }}/mysql.conf.d/mysqld.cnf"
      regexp: "^bind-address"
      replace: "#bind-address =127.0.0.1"

- name: Restart mysql
  become: yes
  service:
      name: "mysql"
      state: "restarted"

- name: update mysql root password for all root accounts
  become: yes
  mysql_user: 
      name: "root" 
      host: "{{ item }}"
      password: "{{ mysql_root_db_pass }}"
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: remove the test database
  become: yes
  mysql_db: 
      name: "test" 
      state: "absent"

- name: Create the database
  become: yes
  mysql_db: 
      name: "{{ item.name }}" 
      state: "present"
  with_items: "{{ mysql_db }}"

- name: Create the database users
  become: yes
  mysql_user: 
      name: "{{ item[0]['name'] }}"
      password: "{{ item[0].pass| default('dbpass') }}"
      priv: "{{ item[0].priv | default('{{ item[0].name }}.*:ALL') }}" 
      state: "present" 
      host: "{{ item[1] }}"
      append_privs: "yes"
  with_nested: 
    - "{{ mysql_users }}"
    - ['localhost' , '%']
