---
neutron_dbpass: "openstack"
neutron_pass: "openstack"

neutron_pkgs:
      - neutron-server 
      - neutron-plugin-ml2
      # for linxubridge
      #- neutron-linuxbridge-agent 
      - neutron-l3-agent 
      - neutron-dhcp-agent
      - neutron-metadata-agent
      # for ovs
      - openvswitch-switch
      - neutron-openvswitch-agent

neutron_services: 
    - "nova-api"
    - "neutron-server"
    # for linuxbridge
    #- "neutron-linuxbridge-agent"
    - "neutron-dhcp-agent"
    - "neutron-metadata-agent"
    - "neutron-l3-agent"
    # for ovs
    - "openvswitch-switch"
    - "neutron-openvswitch-agent"

neutron_conf_dir: "/etc/neutron"
rabbit_pass: "openstack"
nova_pass: "openstack"
ml2_plugin_conf_dir: "/etc/neutron/plugins/ml2"
metadata_secret: "openstack"

neutron_conf:
    DEFAULT:
        core_plugin: "ml2"
        service_plugins: "router"
        allow_overlapping_ips: True
        transport_url: "rabbit://openstack:{{ rabbit_pass }}@controller"
        auth_strategy: "keystone"
        notify_nova_on_port_status_changes: True
        notify_nova_on_port_data_changes: True
    database:
        connection: "mysql+pymysql://neutron:{{ neutron_dbpass }}@controller/neutron"
    keystone_authtoken:
        auth_uri: "http://controller:5000"
        auth_url: "http://controller:35357"
        memcached_servers: "controller:11211"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        project_name: "service"
        username: "neutron"
        password: "{{ neutron_pass }}"
    nova:
        auth_url: "http://controller:35357"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        region_name: "RegionOne"
        project_name: "service"
        username: "nova"
        password: "{{ nova_pass }}"
    agent:
        root_helper: "sudo /usr/bin/neutron-rootwrap /etc/neutron/rootwrap.conf"

ml2_neutron_plugin_conf:
    ml2:
        # for Linuxbridge
        #type_drivers: "flat,vlan,vxlan"
        #tenant_network_types: "vxlan"
        #mechanism_drivers: "linuxbridge,l2population"
        type_drivers: "flat,gre,vxlan"
        tenant_network_types: "vxlan,gre"
        mechanism_drivers: "openvswitch,l2population"
        extension_drivers: "port_security"
    ml2_type_flat:
        # flat_networks: "provider"
        # for ovs
        flat_networks: "*"
    ml2_type_vxlan:
        vni_ranges: "1:1000"
    securitygroup:
        enable_ipset: True
        #for ovs
        firewall_driver: "iptables_hybrid"
    #for OVS
    ml2_type_vlan:
      network_vlan_ranges: "external,vlan:1:1000"
    ml2_type_gre:
      tunnel_id_ranges: "1:1000"

ml2_linuxbridge_agent_conf:
    linuxbridge:
        physical_interface_mappings: "provider:eno3"
    vxlan:
        enable_vxlan: True
        local_ip: "{{ ansible_eno2['ipv4']['address']| default('10.0.0.1') }}"
        l2_population: True
    securitygroup:
        enable_security_group: True
        firewall_driver: "neutron.agent.linux.iptables_firewall.IptablesFirewallDriver"

l3_agent_conf:
    DEFAULT:
        # for linuxbridge
        #interface_driver: "neutron.agent.linux.interface.BridgeInterfaceDriver"    
        interface_driver: "neutron.agent.linux.interface.OVSInterfaceDriver"
        external_network_bridge: ""

dhcp_agent_conf:
    DEFAULT:
        # for linuxbridge
        #interface_driver: "neutron.agent.linux.interface.BridgeInterfaceDriver"
        interface_driver: "neutron.agent.linux.interface.OVSInterfaceDriver"
        dhcp_driver: "neutron.agent.linux.dhcp.Dnsmasq"
        enable_isolated_metadata: True    

metadata_agent_conf:
    DEFAULT:
        nova_metadata_ip: "controller"
        metadata_proxy_shared_secret: "{{ metadata_secret }}"

ovs_agent_conf:
    ovs:
      local_ip: "{{ ansible_eno2['ipv4']['address']| default('10.0.0.1') }}"
      bridge_mappings: "provider:br-ex"
    agent:
      tunnel_types: "vxlan,gre"
      l2_population: True
    securitygroup:
      firewall_driver: "iptables_hybrid"


