---

keystone_pkgs:
          - "keystone"

keystone_service: "keystone"
keystone_conf_dir: "/etc/keystone"

apache_service: "apache2"
apache_conf_dir: "/etc/apache2"

default_sqlite_db: "/var/lib/keystone/keystone.db"

config:
  DEFAULT:
    log_dir: "/var/log/keystone"
  database:        
    connection: "mysql+pymysql://keystone:{{ keystone_dbpass }}@controller/keystone"
  token:        
    expiration: 7200
    provider: "fernet"

apache_conf:
    ServerName: "controller"

admin_account_env:        
    OS_USERNAME: "admin"
    OS_PASSWORD: "{{ admin_pass }}"
    OS_PROJECT_NAME: "admin"
    OS_USER_DOMAIN_NAME: "Default"
    OS_PROJECT_DOMAIN_NAME: "Default"
    OS_AUTH_URL: "http://controller:35357/v3"
    OS_IDENTITY_API_VERSION: 3
    OS_IMAGE_API_VERSION: 2

