---
nova_dbpass: "openstack"
nova_pass: "openstack"

nova_controller_pkgs:
          - nova-api 
          - nova-conductor 
          - nova-consoleauth
          - nova-novncproxy 
          - nova-scheduler

nova_services: 
        - "nova-consoleauth"
        - "nova-api"
        - "nova-scheduler"
        - "nova-conductor"
        - "nova-novncproxy"

nova_conf_dir: "/etc/nova"

neutron_pass: "openstack"
metadata_secret: "openstack"

nova_conf:
    DEFAULT:
        transport_url: "rabbit://openstack:openstack@controller"
        auth_strategy: "keystone"
        my_ip: "{{ ansible_enp0s8['ipv4']['address']| default('10.0.0.1') }}"
        use_neutron: True
        firewall_driver: "nova.virt.firewall.NoopFirewallDriver"
        dhcpbridge_flagfile: "/etc/nova/nova.conf"
        dhcpbridge: "/usr/bin/nova-dhcpbridge"
        state_path: "/var/lib/nova"
        force_dhcp_release: True
        verbose: True
        ec2_private_dns_show_ip: True
        enabled_apis: "osapi_compute,metadata"
    api_database:
        connection: "mysql+pymysql://nova:{{ nova_dbpass }}@controller/nova_api"
    database:
        connection: "mysql+pymysql://nova:{{ nova_dbpass }}@controller/nova"
    keystone_authtoken:
        auth_uri: "http://controller:5000"
        auth_url: "http://controller:35357"
        memcached_servers: "controller:11211"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        project_name: "service"
        username: "nova"
        password: "{{ nova_pass }}"
    vnc:
        vncserver_listen: "$my_ip"
        vncserver_proxyclient_address: "$my_ip"
    glance:
        api_servers: "http://controller:9292"
    oslo_concurrency:
        lock_path: "/var/lib/nova/tmp"
    libvirt:
        use_virtio_for_bridges: True
    wsgi:
        api_paste_config: "/etc/nova/api-paste.ini"
    neutron:
        url: "http://controller:9696"
        auth_url: "http://controller:35357"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        region_name: "RegionOne"
        project_name: "service"
        username: "neutron"
        password: "{{ neutron_pass }}"
        service_metadata_proxy: True
        metadata_proxy_shared_secret: "{{ metadata_secret }}"
