---

- name: Enable SSH password authentication
  become: yes
  replace:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PasswordAuthentication no"
      replace: "PasswordAuthentication yes"

- name: Add OpenStack repository
  become: yes
  shell: "add-apt-repository -y cloud-archive:newton"
#  apt_repository: 
#      repo: "cloud-archive:newton"
#      state: present


- name: Apt distupgrade
  become: yes
  apt:
      upgrade: dist
      update_cache: yes

- name: Install the common packages
  become: yes
  apt: 
      name: "{{ item }}"
      state: "latest"
      update_cache: yes 
#      upgrade: "dist"
  with_items: common_pkgs

- name: Install shade with pip
  become: yes
  pip:
      name: shade

- name: Change hosts file
  become: yes
  template:
      src: "hosts.j2"
      dest: "/etc/hosts"
