---

- name: Enable SSH password authentication
  become: yes
  replace:
      dest: "/etc/ssh/sshd_config"
      regexp: "^PasswordAuthentication no"
      replace: "PasswordAuthentication yes"

- name: Restart SSH service
  become: yes
  service:
      name: "ssh"
      state: "restarted"

- name: Add OpenStack repository
  become: yes
  shell: "add-apt-repository -y cloud-archive:pike"
#  apt_repository: 
#      repo: "cloud-archive:newton"
#      state: present


- name: Apt distupgrade
  become: yes
  apt:
      upgrade: "dist"
      update_cache: "yes"

- name: Install the common packages
  become: yes
  apt: 
      name: "{{ item }}"
      state: "installed"
      update_cache: "yes" 
#      upgrade: "dist"
  with_items: "{{ common_pkgs }}"

- name: Install shade with pip
  become: yes
  pip:
      name: "shade"
      version: 1.19.0

- name: Install OpenstackClient with pip
  become: yes
  pip:
      name: "python-openstackclient"

#- name: Install novaclient v6.0
#  become: yes
#  pip:
#     name: "python-novaclient==6.0.0"
#     state: "present"

- name: Change hosts file
  become: yes
  template:
      src: "hosts.j2"
      dest: "/etc/hosts"

- name: This makes OVS works in container
  become: yes
  shell: "echo exit 0 > /usr/sbin/policy-rc.d"
