---

mysql_pkgs:
      - python-pymysql
      - mysql-server
      - python-mysqldb

mysql_service: mysql
mysql_conf_dir: "/etc/mysql/mysql.conf.d/"

mysql_port: 3306
mysql_bind_address: "0.0.0.0"
mysql_root_db_pass: entertm1

mysql_db: 
      - name: keystone
        replicate: no

mysql_users:
      - name: keystone
        pass: keystonepassword
        priv: "keystone.*:ALL"

mysqld_options:
      bind-address: "{{ mysql_bind_address }}"
      default-storage-engine: "innodb"
      "innodb_file_per_table"
      max_connections:  4096
      collation-server: "utf8_general_ci"
      character-set-server:  "utf8"

