---

mysql_pkgs:
      - python-pymysql
      - mysql-server
      - python-mysqldb

mysql_service: mysql
mysql_conf_dir: "/etc/mysql"
openstack_mysql_conf_dir: "/etc/mysql/conf.d"

mysql_port: 3306
mysql_bind_address: "{{ ansible_eno2['ipv4']['address']| default('10.0.0.1') }}"
mysql_root_db_pass: "openstack"

mysql_db: 
      - name: "keystone"
      - name: "glance"
      - name: "nova"
      - name: "nova_api" 
      - name: "neutron"
      - name: "cinder"

mysql_users:
      - name: "keystone"
        pass: "openstack"
        priv: "keystone.*:ALL"
      - name: "glance"
        pass: "openstack"
        priv: "glance.*:ALL"
      - name: "nova"
        pass: "openstack"
        priv: "nova.*:ALL"
      - name: "nova"
        pass: "openstack"
        priv: "nova_api.*:ALL"
      - name: "neutron"
        pass: "openstack"
        priv: "neutron.*:ALL"
      - name: "cinder"
        pass: "openstack"
        priv: "cinder.*:ALL"

mysqld_options:
      bind-address: "{{ mysql_bind_address }}"
      default-storage-engine: "innodb"
      max_connections:  4096
      collation-server: "utf8_general_ci"
      character-set-server:  "utf8"

