---

- name: Install the keystone packages
  become: yes
  apt: 
      name: "{{ item }}"
      state: "latest"
      update_cache: yes
  with_items: "{{ keystone_pkgs }}"

- name: Copy keystone config file 
  become: yes
  template: 
      src: "keystone.j2"
      dest: "{{ keystone_conf_dir }}/keystone.conf"
  #notify: restart keystone

- name: Populate the identity service database
  become: yes
  #become_user: "keystone"
  shell: 'su -s /bin/sh -c "keystone-manage db_sync" keystone'
  #shell: "keystone-manage db_sync"

- name: Initialize Fernet key repositories
  become: yes
  shell: 'keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone'

- name: Credential setup
  become: yes  
  shell: 'keystone-manage credential_setup --keystone-user keystone --keystone-group keystone'

- name: Bootstrap the identity service
  become: yes
  shell: 'keystone-manage bootstrap --bootstrap-password {{ admin_pass }} --bootstrap-admin-url http://controller:35357/v3/ --bootstrap-internal-url http://controller:35357/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne'

- name: Edit apache2 config
  become: yes
  lineinfile:
      dest: "{{ apache_conf_dir }}/apache2.conf"
      regexp: "^ServerName"
      line: "ServerName controller"
  #notify: restart apache2

- name: Restart apache2
  become: yes
  service:
      name: "apache2"
      state: "restarted"

- name: Remove default SQLite database
  become: yes
  file:
      path: "{{ default_sqlite_db }}"
      state: "absent"

- name: Create admin account environment file
  template:
      src: "admin.j2"
      dest: "{{ ansible_env.HOME }}/adminrc"

#- name: Set the environment
#  shell: "source {{ ansible_env.HOME }}/adminrc"

- name: Create service project
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  os_project:
      state: "present"
      name: "service"
      description: "Service Project"
      domain_id: "default"
      enabled: True

- name: Create demo project
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  os_project:
      state: "present"
      name: "demo"
      description: "Demo Project"
      domain_id: "default"
      enabled: True

- name: Create demo user
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  os_user:
      state: "present"
      name: "demo"
      password: "{{ demo_password }}"
      default_project: "demo"
      domain: "default"
      enabled: True

- name: Create user role
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  shell: "openstack role create user"

#- name: Add the user role to the demo project and user
#  os_user_role:
#      user: "demo"
#      project: "demo"
#      role: "user"
#      state: present

- name: Add the user role to the demo project and user
  environment:
      OS_USERNAME: "admin"
      OS_PASSWORD: "{{ admin_pass }}"
      OS_PROJECT_NAME: "admin"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_NAME: "Default"
      OS_AUTH_URL: "http://controller:35357/v3"
      OS_IDENTITY_API_VERSION: 3
  shell: "openstack role add --project demo --user demo user"




