---

common_pkgs:
          - software-properties-common
          - python-openstackclient
          - python-pip
hosts_options:
          # for lendulet
          controller: "10.0.0.7"
          compute1: "10.0.0.1"
          compute2: "10.0.0.6"
          compute3: "10.0.0.11"
          compute4: "10.0.0.12"
          compute5: "10.0.0.4"
          # for taska
          #controller: "10.0.0.17"
          #compute1: "10.0.0.15"
          #compute2: "10.0.0.16"
