---

common_pkgs:
          - "software-properties-common"
          #- "python-openstackclient"
          - "python-pip"
          - "build-essential" 
          - "libssl-dev"
          - "libffi-dev" 
          - "python-dev"

hosts_options: "{{ hosts }}"

admin_pass: "openstack"
demo_pass: "openstack"

glance_dbpass: "openstack"
glance_pass: "openstack"

keystone_dbpass: "openstack"

neutron_dbpass: "openstack"
neutron_pass: "openstack"
metadata_secret: "openstack"

nova_dbpass: "openstack"
nova_pass: "openstack"

cinder_dbpass: "openstack"
cinder_pass: "openstack"

placement_pass: "openstack"

hosts:
    controller: "{{ management_interface_address_controller }}"
    "{{ ansible_hostname }}": "127.0.0.1"

management_interface_name_controller: "eth0"
#management_interface_address_controller: "{{ ansible_eth0['ipv4']['address'] }}"
management_interface_address_controller: "172.18.0.2"

public_interface_name_controller: "eth0"
public_interface_address_controller: "{{ ansible_eth0['ipv4']['address'] }}"

management_interface_name_compute: "eth0"
management_interface_address_compute: "{{ ansible_eth0['ipv4']['address'] }}"

public_interface_name_compute: "eth0"
public_interface_address_compute: "{{ ansible_eth0['ipv4']['address'] }}"


rabbit_pass: "openstack"
rabbit_users: "openstack"

mysql_root_db_pass: "openstack"

fake: False
