---

common_pkgs:
          - software-properties-common
          - python-openstackclient
          - python-pip
hosts_options:
          controller: "{{ ansible_enp0s8['ipv4']['address']| default('10.0.0.1') }}"
          compute1: "{{ ansible_enp0s8['ipv4']['address']| default('10.0.0.2') }}"
