---

- name: Install the memcached packages
  become: yes
  apt: 
      name: "{{ item }}" 
      state: "installed" 
      update_cache: yes
  with_items: memcached_pkgs

- name: Change memcached conf
  become: yes
  lineinfile:
      dest: "{{ memcached_conf_dir}}/memcached.conf"
      regexp: "^-l 127.0.0.1"
      line: "{{ ansible_eno2['ipv4']['address']| default('10.0.0.1') }}"
  #notify: restart memcached

- name: Restart memcached service
  become: yes
  service:
      name: "memcached"
      state: "restarted"
