---
glance_pkgs:
      - "glance"

glance_services: 
    - "glance-registry"
    - "glance-api"

glance_conf_dir: "/etc/glance"

glance_conf_api:
    database:
        connection: "mysql+pymysql://glance:{{ glance_dbpass }}@controller/glance"
        backend: "sqlalchemy"
    image_format:
        disk_formats: "ami,ari,aki,vhd,vhdx,vmdk,raw,qcow2,vdi,iso,root-tar"
    keystone_authtoken:
        auth_uri: "http://controller:5000"
        auth_url: "http://controller:35357"
        memcached_servers: "controller:11211"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        project_name: "service"
        username: "glance"
        password: "{{ glance_pass }}"
    paste_deploy:
        flavor: "keystone"
    glance_store:
        stores: "file,http"
        default_store: "file"
        filesystem_store_datadir: "var/lib/glance/images/"

glance_conf_registry:
    database:
        connection: "mysql+pymysql://glance:{{ glance_dbpass }}@controller/glance"
        backend: "sqlalchemy"
    keystone_authtoken:
        auth_uri: "http://controller:5000"
        auth_url: "http://controller:35357"
        memcached_servers: "controller:11211"
        auth_type: "password"
        project_domain_name: "Default"
        user_domain_name: "Default"
        project_name: "service"
        username: "glance"
        password: "{{ glance_pass }}"
    paste_deploy:    
        flavor: "keystone"
